# Generated by Django 5.2.17 on 2026-09-17 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0009_sku_readable_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='AsOne Logistics', max_length=200)),
                ('timezone', models.CharField(choices=[('Africa/Kampala', 'East Africa Time (EAT) / Kampala (UTC+3)')], default='Africa/Kampala', max_length=64)),
                ('currency', models.CharField(choices=[('UGX', 'Ugandan Shilling (UGX)')], default='UGX', max_length=8)),
                ('default_minimum_stock_threshold', models.PositiveIntegerField(default=150, help_text="Suggested starting value when setting a new SKU's minimum stock level. Does not change any level already set.")),
                ('critical_safety_buffer_percent', models.PositiveIntegerField(default=10, help_text='How far below the minimum counts as critical, as a percentage of it.')),
                ('auto_trigger_tailoring_center_reorder', models.BooleanField(default=True, help_text='Stored for a future automatic-reorder feature. Nothing places a production order from this today — see procurement/services.py for how production orders are actually raised.')),
                ('low_stock_alerts_enabled', models.BooleanField(default=True)),
                ('receipt_discrepancy_alerts_enabled', models.BooleanField(default=True)),
                ('backorder_allocation_alerts_enabled', models.BooleanField(default=True)),
                ('auto_sync_interval_minutes', models.PositiveIntegerField(default=5, help_text='Stored for a future offline mode. No code reads this value today.')),
                ('offline_data_retention_days', models.PositiveIntegerField(default=30, help_text='Stored for a future offline mode. No code reads this value today.')),
                ('default_paper_size', models.CharField(choices=[('A4', 'A4 (Standard Ugandan Format)'), ('LETTER', 'US Letter')], default='A4', max_length=16)),
                ('packing_list_layout', models.CharField(choices=[('SKU_GROUPED', 'Standard SKU-Grouped'), ('ORDER_GROUPED', 'Grouped by Order')], default='SKU_GROUPED', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_warehouse', models.ForeignKey(blank=True, help_text="The site a new session's warehouse filter starts on. Nullable: a fresh install has no warehouses yet, and 'all warehouses' is a legitimate starting point too.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.warehouse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
