# Generated by Django 5.2.17 on 2026-09-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='auto_sync_interval_minutes',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='offline_data_retention_days',
        ),
    ]
