# Generated by Django 5.2.17 on 2026-09-03 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_email_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(editable=False, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'login verification code',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consumed_at'], name='accounts_lo_user_id_ada8f2_idx')],
            },
        ),
    ]
