# Generated by Django 5.2.17 on 2026-08-28 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_kit_kititem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # AsOne's "Transaction #". Created before the table, because save()
        # draws from it the first time a movement is posted. A sequence never
        # goes backwards, so a transaction number is never reused — which is
        # what makes the ledger readable as a document trail.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS inventory_movement_seq START WITH 1000001;",
            reverse_sql="DROP SEQUENCE IF EXISTS inventory_movement_seq;",
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text="AsOne's Transaction #. System assigned, never reused.", max_length=16, unique=True)),
                ('quantity', models.IntegerField(help_text='Signed: positive into the warehouse, negative out of it.')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt from a Tailoring Center'), ('ADJUSTMENT', 'Inventory adjustment'), ('TRANSFER_IN', 'Transfer in from another warehouse'), ('TRANSFER_OUT', 'Transfer out to another warehouse'), ('PICK', 'Picked for a school order'), ('SHIPMENT', 'Shipped to a school'), ('RETURN', 'Returned by a school'), ('DAMAGE', 'Damaged or lost')], max_length=16)),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PICK', 'Picked'), ('SHIPPED', 'Shipped')], default='AVAILABLE', max_length=12)),
                ('unit_value', models.DecimalField(decimal_places=2, help_text='Value per unit at the time of the movement. Never recalculated.', max_digits=12)),
                ('document_number', models.CharField(db_index=True, help_text='The document that caused this movement.', max_length=32)),
                ('source', models.CharField(blank=True, help_text='Where it came from, e.g. "Idudi".', max_length=120)),
                ('destination', models.CharField(blank=True, help_text='Where it went, for outbound movements.', max_length=120)),
                ('occurred_on', models.DateField(help_text='The date the movement actually happened.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.warehouse')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
                'indexes': [models.Index(fields=['warehouse', 'sku', 'stock_status'], name='inventory_s_warehou_de3712_idx'), models.Index(fields=['sku', '-occurred_on'], name='inventory_s_sku_id_a0be19_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='stock_movement_is_not_zero'), models.CheckConstraint(condition=models.Q(('unit_value__gte', 0)), name='stock_movement_value_is_not_negative')],
            },
        ),
    ]
