# Generated by Django 5.2.17 on 2026-08-28 13:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_stock_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short identifier, e.g. "DMG". Appears on adjustment documents.', max_length=20)),
                ('name', models.CharField(help_text='For example "Damaged in transit".', max_length=120)),
                ('description', models.TextField(blank=True, help_text='When to use this code, for whoever is choosing one.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive codes stay on past adjustments but cannot be chosen for new ones.')),
            ],
            options={
                'verbose_name': 'inventory adjustment reason code',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_reason_code'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_reason_code_name')],
            },
        ),
    ]
