# Generated by Django 5.2.17 on 2026-08-29 10:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_case_insensitive_names'),
        ('inventory', '0002_reason_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Transfer numbers, drawn the same way as transaction numbers: atomic
        # under concurrency and never reused, because the number appears on a
        # document that travels with the goods.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS inventory_transfer_seq START WITH 5001;",
            reverse_sql="DROP SEQUENCE IF EXISTS inventory_transfer_seq;",
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='System assigned. Unique forever, never reused.', max_length=16, unique=True)),
                ('transfer_date', models.DateField(help_text='The date the stock actually moved.')),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='When this transfer was posted to the ledger. Blank means not yet posted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='catalog.warehouse')),
                ('reason_code', models.ForeignKey(blank=True, help_text='Optional. Why this rebalancing was needed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.reasoncode')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='catalog.warehouse')),
            ],
            options={
                'ordering': ['-transfer_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, help_text='Set when the transfer is posted, from the value at the source warehouse.', max_digits=12, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sku')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.warehousetransfer')),
            ],
            options={
                'ordering': ['sku__description'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehousetransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True), name='transfer_between_different_warehouses'),
        ),
        migrations.AddConstraint(
            model_name='warehousetransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'sku'), name='unique_sku_per_transfer'),
        ),
    ]
