# Generated by Django 5.2.17 on 2026-08-29 20:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_case_insensitive_names'),
        ('inventory', '0004_reason_code_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Adjustment numbers, drawn the same way as transaction and transfer
        # numbers: atomic under concurrency and never reused, because the
        # number is what a reversing adjustment (Wave 3) will reference.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS inventory_adjustment_seq START WITH 9001;",
            reverse_sql="DROP SEQUENCE IF EXISTS inventory_adjustment_seq;",
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='System assigned. Unique forever, never reused.', max_length=16, unique=True)),
                ('quantity', models.PositiveIntegerField(help_text='How many units changed. The reason code decides the direction.', validators=[django.core.validators.MinValueValidator(1)])),
                ('adjustment_date', models.DateField(help_text='The date the change actually happened, e.g. the day of a physical count.')),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, help_text="Set when posted, from the SKU's catalog price on adjustment_date.", max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='When this was posted to the ledger. Blank means not yet posted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reason_code', models.ForeignKey(help_text='Why this adjustment was made. Also decides its direction.', on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.reasoncode')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='catalog.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='catalog.warehouse')),
            ],
            options={
                'ordering': ['-adjustment_date', '-number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='adjustment_quantity_is_positive')],
            },
        ),
    ]
