# Generated by Django 5.2.17 on 2026-08-27 16:31

import catalog.models.pricing
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        # Must come first. GarmentPrice's exclusion constraint combines an
        # equality test on garment_id with an overlap test on a date range,
        # and a stock GiST index cannot do equality on a plain integer —
        # btree_gist is what teaches it how. Creating the extension needs
        # superuser rights on the database the first time it runs.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='For example "10" or "S".', max_length=20, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Smallest first. Ties fall back to name.')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='For example "White Shirt".', max_length=120)),
                ('school_level', models.CharField(choices=[('PS', 'Primary School'), ('HS', 'High School'), ('BOTH', 'Both')], default='BOTH', help_text='Which price list this garment appears on.', max_length=4)),
                ('colour', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive garments stay in reports but cannot be ordered.')),
            ],
            options={
                'ordering': ['name', 'school_level'],
                'constraints': [models.UniqueConstraint(fields=('name', 'school_level'), name='unique_garment_per_level')],
            },
        ),
        migrations.CreateModel(
            name='GarmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Purchase price and selling price — AsOne uses one figure for both.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('active_date', models.DateField(help_text='First day this price applies.')),
                ('expiration_date', models.DateField(blank=True, help_text='First day this price NO LONGER applies. Leave blank for open-ended.', null=True)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.garment')),
            ],
            options={
                'ordering': ['garment', '-active_date'],
                'get_latest_by': 'active_date',
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='garment_price_is_positive'), models.CheckConstraint(condition=models.Q(('expiration_date__isnull', True), ('expiration_date__gt', models.F('active_date')), _connector='OR'), name='garment_price_expires_after_it_starts'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(catalog.models.pricing.DateRange('active_date', 'expiration_date', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('garment', '=')], name='no_overlapping_garment_prices', violation_error_message='This garment already has a price covering part of that period. Close the existing price first.')],
            },
        ),
    ]
