# Generated by Django 5.2.17 on 2026-08-27 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_garment_and_pricing'),
    ]

    operations = [
        # The sequence SKU control numbers are drawn from. Created before the
        # table, because Sku.save() calls nextval() on it the first time a SKU
        # is created.
        #
        # Starts at 100001 so every number is six digits, matching AsOne's own
        # example ("123456 = White Shirt size 10"). A sequence never goes
        # backwards, which is what makes a control number never reused.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS catalog_sku_number_seq START WITH 100001;",
            reverse_sql="DROP SEQUENCE IF EXISTS catalog_sku_number_seq;",
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='System assigned. Unique forever, never reused.', max_length=12, unique=True)),
                ('description', models.CharField(blank=True, help_text='Filled in from the garment and size if left blank.', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive SKUs stay in reports but cannot be ordered.')),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='catalog.garment')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='catalog.size')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='MinimumStockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.PositiveIntegerField(help_text='Stock at or below this level raises a reorder alert.', validators=[django.core.validators.MinValueValidator(0)])),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minimum_levels', to='catalog.warehouse')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minimum_levels', to='catalog.sku')),
            ],
            options={
                'ordering': ['warehouse', 'sku'],
            },
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(fields=('garment', 'size'), name='unique_sku_per_garment_size'),
        ),
        migrations.AddConstraint(
            model_name='minimumstocklevel',
            constraint=models.UniqueConstraint(fields=('sku', 'warehouse'), name='unique_minimum_per_sku_warehouse'),
        ),
    ]
