# Generated by Django 5.2.17 on 2026-08-27 16:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_skus_and_minimum_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentprice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Purchase price and selling price — AsOne uses one figure for both.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
