# Generated by Django 5.2.17 on 2026-08-27 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_price_validator_uses_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_number', models.CharField(help_text='Entered by whoever creates the kit, e.g. "PS-STARTER-01".', max_length=20, unique=True)),
                ('name', models.CharField(help_text='For example "PS Starter Kit".', max_length=120)),
                ('school_level', models.CharField(choices=[('PS', 'Primary School'), ('HS', 'High School')], max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive kits stay in reports but cannot be ordered.')),
            ],
            options={
                'ordering': ['school_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='How many of this SKU one kit contains.', validators=[django.core.validators.MinValueValidator(1)])),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.kit')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='catalog.sku')),
            ],
            options={
                'ordering': ['kit', 'sku'],
                'constraints': [models.UniqueConstraint(fields=('kit', 'sku'), name='unique_sku_per_kit')],
            },
        ),
    ]
