# Generated by Django 5.2.17 on 2026-08-28 12:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_kit_kititem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tailoringcenter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='garment',
            name='unique_garment_per_level',
        ),
        migrations.AlterField(
            model_name='kit',
            name='kit_number',
            field=models.CharField(help_text='Entered by whoever creates the kit, e.g. "PS-STARTER-01".', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(help_text='For example "10" or "S".', max_length=20),
        ),
        migrations.AlterField(
            model_name='tailoringcenter',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='garment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('school_level'), name='unique_garment_per_level'),
        ),
        migrations.AddConstraint(
            model_name='kit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('kit_number'), name='unique_kit_number'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_school_name'),
        ),
        migrations.AddConstraint(
            model_name='size',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_size_name'),
        ),
        migrations.AddConstraint(
            model_name='tailoringcenter',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_tailoring_center_name'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_warehouse_name'),
        ),
    ]
