# Generated by Django 5.2.17 on 2026-09-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_case_insensitive_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, help_text='A closed site stays in reports but takes no new work.'),
        ),
        migrations.AddField(
            model_name='tailoringcenter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='A closed site stays in reports but takes no new work.'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='A closed site stays in reports but takes no new work.'),
        ),
    ]
