# Generated by Django 5.2.17 on 2026-08-28 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_price_validator_uses_decimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The sequences document numbers are drawn from. Created before the
        # tables, because save() calls nextval() the first time an order is
        # raised.
        #
        # Separate sequences so the two numbering series are independent —
        # GO-100001 and PO-100001 can both exist, and a gap in one does not
        # appear in the other. A sequence never goes backwards, which is what
        # makes a cancelled order's number stay retired.
        migrations.RunSQL(
            sql=[
                "CREATE SEQUENCE IF NOT EXISTS procurement_group_order_seq START WITH 100001;",
                "CREATE SEQUENCE IF NOT EXISTS procurement_production_order_seq START WITH 100001;",
            ],
            reverse_sql=[
                "DROP SEQUENCE IF EXISTS procurement_group_order_seq;",
                "DROP SEQUENCE IF EXISTS procurement_production_order_seq;",
            ],
        ),
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='System assigned. Unique forever, never reused.', max_length=16, unique=True)),
                ('order_date', models.DateField(help_text='The date the order was placed.')),
                ('due_in_warehouse_date', models.DateField(blank=True, help_text='When the goods are expected.', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group order',
                'ordering': ['-order_date', '-number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='System assigned. Unique forever, never reused.', max_length=16, unique=True)),
                ('order_date', models.DateField(help_text='The date the order was placed.')),
                ('due_in_warehouse_date', models.DateField(blank=True, help_text='When the goods are expected.', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group_order', models.ForeignKey(blank=True, help_text='The group order this breaks down, where there is one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='procurement.grouporder')),
                ('tailoring_center', models.ForeignKey(help_text="Who makes the goods. Any TC, not only the warehouse's primary one.", on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='catalog.tailoringcenter')),
                ('warehouse', models.ForeignKey(help_text='Who receives the goods.', on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='catalog.warehouse')),
            ],
            options={
                'verbose_name': 'production order',
                'ordering': ['-order_date', '-number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='The price when the order was placed. Not recalculated later.', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.productionorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sku')),
            ],
            options={
                'ordering': ['sku__description'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='The price when the order was placed. Not recalculated later.', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.grouporder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sku')),
            ],
            options={
                'ordering': ['sku__description'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('order', 'sku'), name='unique_sku_per_group_order')],
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['warehouse', 'status'], name='procurement_warehou_bb83b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionorderline',
            constraint=models.UniqueConstraint(fields=('order', 'sku'), name='unique_sku_per_production_order'),
        ),
    ]
