# Generated by Django 5.2.17 on 2026-08-28 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_kit_kititem'),
        ('procurement', '0001_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS procurement_receipt_seq START WITH 100001;",
            reverse_sql="DROP SEQUENCE IF EXISTS procurement_receipt_seq;",
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='System assigned. Unique forever, never reused.', max_length=16, unique=True)),
                ('packing_list_number', models.CharField(help_text="From the TC's handwritten packing list, exactly as written.", max_length=60)),
                ('date_received', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='When this receipt was posted to inventory. Blank means not yet posted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(help_text='What this delivery is against.', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='procurement.productionorder')),
            ],
            options={
                'ordering': ['-date_received', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField(help_text='What was actually counted off the van.', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_on_packing_list', models.PositiveIntegerField(blank=True, help_text="What the TC's handwritten packing list claimed. Blank if it did not say.", null=True)),
                ('discrepancy_note', models.CharField(blank=True, help_text='Why the count differs — damaged in transit, miscount, short shipment.', max_length=200)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.receipt')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sku')),
            ],
            options={
                'ordering': ['sku__description'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['production_order', '-date_received'], name='procurement_product_e62436_idx'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'sku'), name='unique_sku_per_receipt'),
        ),
    ]
