# Generated by Django 5.2.17 on 2026-09-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_receipt_line_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='carrier_name',
            field=models.CharField(blank=True, help_text='The carrier or driver who delivered it, as given at the gate.', max_length=120),
        ),
    ]
