# Generated by Django 5.2.17 on 2026-08-31 13:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_case_insensitive_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The order number, which is also the invoice number a school hands
        # to a parent. Atomic under concurrency and never reused — it has to
        # mean one order forever.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS orders_school_order_seq START WITH 20001;",
            reverse_sql="DROP SEQUENCE IF EXISTS orders_school_order_seq;",
        ),
        migrations.CreateModel(
            name='SchoolOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='System assigned. Also the invoice number. Never reused.', max_length=16, unique=True)),
                ('student_name', models.CharField(help_text='The student this uniform is for. Free text — students have no accounts.', max_length=150)),
                ('order_date', models.DateField(help_text='The date the school placed it.')),
                ('status', models.CharField(choices=[('HOLD', 'On hold — awaiting payment'), ('RELEASED', 'Released to the warehouse'), ('PICKED', 'Picked'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='HOLD', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.school')),
            ],
            options={
                'ordering': ['-order_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='SchoolOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='The price on the day the order was placed. Never recalculated.', max_digits=12)),
                ('from_kit', models.ForeignKey(blank=True, help_text='The kit this line was exploded from, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.kit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.schoolorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sku')),
            ],
            options={
                'ordering': ['sku__description'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolorder',
            index=models.Index(fields=['school', 'status'], name='orders_scho_school__715146_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolorder',
            index=models.Index(fields=['student_name'], name='orders_scho_student_c3be79_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolorderline',
            constraint=models.UniqueConstraint(fields=('order', 'sku', 'from_kit'), name='unique_sku_per_order_source'),
        ),
    ]
