# Generated by Django 5.2.17 on 2026-09-02 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancellation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolorder',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Whatever identifies the payment — a receipt number, a mobile money reference. Free text until AsOne says what School Monitor is.', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolorder',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolorder',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
