# Generated by Django 5.2.17 on 2026-09-02 14:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_case_insensitive_names'),
        ('orders', '0003_order_release'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The shipment number. Same reasoning as the order number: atomic
        # under concurrency and never reused, because it is what a school
        # quotes when a parcel does not arrive.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS orders_shipment_seq START WITH 5001;",
            reverse_sql="DROP SEQUENCE IF EXISTS orders_shipment_seq;",
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='System assigned. Never reused.', max_length=16, unique=True)),
                ('shipped_on', models.DateField(help_text='The day it left the warehouse.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waybill_number', models.CharField(blank=True, help_text="The carrier's reference, if there is one.", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('from_warehouse', models.ForeignKey(help_text="Where this actually left from, which is not always the school's own warehouse.", on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='catalog.warehouse')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='orders.schoolorder')),
                ('shipped_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shipped_on', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.shipment')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sku')),
            ],
            options={
                'ordering': ['sku__description'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order'], name='orders_ship_order_i_18d8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['from_warehouse', 'shipped_on'], name='orders_ship_from_wa_9d28a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentline',
            constraint=models.UniqueConstraint(fields=('shipment', 'sku'), name='unique_sku_per_shipment'),
        ),
    ]
