# Generated by Django 5.2.17 on 2026-09-02 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_case_insensitive_names'),
        ('orders', '0004_shipments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('OPEN', 'Outstanding — no warehouse assigned'), ('ASSIGNED', 'Assigned to a warehouse with stock'), ('FILLED', 'Shipped to the school'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('filled_by_warehouse', models.ForeignKey(blank=True, help_text="The warehouse that took this on. Not the school's own — that is the one that ran short.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backorders_accepted', to='catalog.warehouse')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorders', to='orders.schoolorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sku')),
            ],
            options={
                'ordering': ['created_at', 'sku__description'],
                'indexes': [models.Index(fields=['status'], name='orders_back_status_1d6ff7_idx'), models.Index(fields=['filled_by_warehouse', 'status'], name='orders_back_filled__7d73b8_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'sku'), name='unique_backorder_per_order_sku')],
            },
        ),
    ]
