# Generated by Django 5.2.17 on 2026-09-09 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_backorders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='receipt_notes',
            field=models.TextField(blank=True, help_text='Anything wrong with the parcel — short, damaged, wrong student.'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolorder',
            name='status',
            field=models.CharField(choices=[('HOLD', 'On hold — awaiting payment'), ('RELEASED', 'Released to the warehouse'), ('PICKED', 'Picked'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Received by the school'), ('CANCELLED', 'Cancelled')], default='HOLD', max_length=12),
        ),
    ]
