"""F42 — one despatch, many orders.

AsOne's checklist asks for a "consolidated weekly despatch" per school, with
the school handing parcels to students by name off the packing list. A
shipment was addressed to a single order, so this moves the consignee up to
the school and pushes the order link down onto the lines.

Written by hand rather than autogenerated, because the autogenerated version
drops `Shipment.order` in the same breath as adding the new columns — which
would throw away the link every existing shipment depends on. The order here
matters: widen, backfill, then narrow.
"""

from django.db import migrations, models
import django.db.models.deletion


def carry_orders_onto_the_lines(apps, schema_editor):
    """Every existing shipment carries exactly one order. Say so explicitly."""
    Shipment = apps.get_model("orders", "Shipment")

    for shipment in Shipment.objects.select_related("order").all():
        shipment.school_id = shipment.order.school_id
        shipment.save(update_fields=["school"])
        shipment.lines.update(order_id=shipment.order_id)


def put_the_order_back_on_the_shipment(apps, schema_editor):
    """Reverse: a shipment carrying more than one order cannot go back.

    Refusing loudly beats silently keeping whichever order sorted first and
    losing the rest.
    """
    Shipment = apps.get_model("orders", "Shipment")

    for shipment in Shipment.objects.all():
        orders = set(shipment.lines.values_list("order_id", flat=True))
        if len(orders) > 1:
            raise RuntimeError(
                f"{shipment.number} carries {len(orders)} orders. A one-order "
                "shipment cannot represent it, so this migration cannot be "
                "reversed without deciding which orders to drop."
            )
        if orders:
            shipment.order_id = orders.pop()
            shipment.save(update_fields=["order"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0006_order_completion"),
    ]

    operations = [
        # 1 / Widen — both new columns nullable so existing rows survive.
        migrations.AddField(
            model_name="shipment",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="catalog.school",
                help_text="Who receives it. Every order on a shipment belongs to this school.",
            ),
        ),
        migrations.AddField(
            model_name="shipmentline",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_lines",
                to="orders.schoolorder",
                help_text="Which order this line fills, and so which student it is for.",
            ),
        ),
        # 2 / Backfill from the column about to be dropped.
        migrations.RunPython(
            carry_orders_onto_the_lines, put_the_order_back_on_the_shipment
        ),
        # 3 / Narrow — now that every row has a value.
        migrations.AlterField(
            model_name="shipment",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="catalog.school",
                help_text="Who receives it. Every order on a shipment belongs to this school.",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentline",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_lines",
                to="orders.schoolorder",
                help_text="Which order this line fills, and so which student it is for.",
            ),
        ),
        # 4 / The old shape goes.
        migrations.RemoveIndex(model_name="shipment", name="orders_ship_order_i_18d8fc_idx"),
        migrations.RemoveField(model_name="shipment", name="order"),
        # 5 / A SKU is unique per order per shipment, not per shipment: two
        #     students on one van can both get a size 8 shirt.
        migrations.RemoveConstraint(
            model_name="shipmentline", name="unique_sku_per_shipment"
        ),
        migrations.AlterModelOptions(
            name="shipmentline",
            options={"ordering": ["order__number", "sku__description"]},
        ),
        migrations.AddConstraint(
            model_name="shipmentline",
            constraint=models.UniqueConstraint(
                fields=("shipment", "order", "sku"),
                name="unique_sku_per_order_per_shipment",
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["school", "-shipped_on"], name="orders_ship_school__5a12b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["received_at"], name="orders_ship_receive_c7a10a_idx"
            ),
        ),
    ]
