# Generated by Django 5.2.17 on 2026-09-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_consolidated_despatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolorder',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='A picking hint for the warehouse. Nothing in the system acts on it.', max_length=8),
        ),
        migrations.AddField(
            model_name='shipment',
            name='carrier_method',
            field=models.CharField(blank=True, help_text='How it travelled — a truck, a route, a courier. As given at the gate.', max_length=120),
        ),
    ]
